package com.kprl.exam.platform.account

import android.app.Activity
import androidx.credentials.CredentialManager
import androidx.credentials.CustomCredential
import androidx.credentials.GetCredentialRequest
import androidx.credentials.exceptions.GetCredentialCancellationException
import com.google.android.gms.tasks.Task
import com.google.android.libraries.identity.googleid.GetSignInWithGoogleOption
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential
import com.google.firebase.FirebaseApp
import com.google.firebase.auth.AuthCredential
import com.google.firebase.auth.EmailAuthProvider
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.auth.FirebaseAuthUserCollisionException
import com.google.firebase.auth.FirebaseUser
import com.google.firebase.auth.GoogleAuthProvider
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException

enum class AccountProvider(val providerId: String) {
    EMAIL("password"),
    GOOGLE("google.com");

    companion object {
        fun from(id: String) = entries.firstOrNull { it.providerId == id }
    }
}

data class AccountSnapshot(
    val isSignedIn: Boolean = false,
    val isAnonymous: Boolean = true,
    val email: String? = null,
    val providers: List<AccountProvider> = emptyList()
)

class AuthCancelledException : Exception()

/**
 * Upgrades the anonymous Firebase session to a permanent account.
 * Linking keeps the same UID, so cloud study data stays attached to the user.
 */
object AuthService {
    private val _account = MutableStateFlow(AccountSnapshot())
    val account: StateFlow<AccountSnapshot> = _account.asStateFlow()

    private var started = false

    fun start() {
        val auth = authOrNull() ?: return
        if (started) return
        started = true
        auth.addAuthStateListener { _account.value = snapshot(it.currentUser) }
    }

    suspend fun continueWithEmail(email: String, password: String, createAccount: Boolean) {
        val auth = requireAuth()
        if (createAccount) {
            linkOrSignIn(auth, EmailAuthProvider.getCredential(email, password))
        } else {
            auth.signInWithEmailAndPassword(email, password).await()
        }
        refresh()
    }

    suspend fun sendPasswordReset(email: String) {
        requireAuth().sendPasswordResetEmail(email).await()
    }

    suspend fun continueWithGoogle(activity: Activity) {
        val auth = requireAuth()
        val webClientId = webClientId(activity)
            ?: throw IllegalStateException("Google sign-in is not configured yet.")

        val request = GetCredentialRequest.Builder()
            .addCredentialOption(GetSignInWithGoogleOption.Builder(webClientId).build())
            .build()

        val result = try {
            CredentialManager.create(activity).getCredential(activity, request)
        } catch (_: GetCredentialCancellationException) {
            throw AuthCancelledException()
        }

        val credential = result.credential
        if (credential !is CustomCredential ||
            credential.type != GoogleIdTokenCredential.TYPE_GOOGLE_ID_TOKEN_CREDENTIAL
        ) {
            throw IllegalStateException("Sign-in did not return a Google token.")
        }
        val idToken = GoogleIdTokenCredential.createFrom(credential.data).idToken
        linkOrSignIn(auth, GoogleAuthProvider.getCredential(idToken, null))
        refresh()
    }

    /** Signs out of the permanent account and returns to a fresh anonymous session. */
    suspend fun signOut(activity: Activity) {
        val auth = requireAuth()
        runCatching {
            CredentialManager.create(activity)
                .clearCredentialState(androidx.credentials.ClearCredentialStateRequest())
        }
        auth.signOut()
        auth.signInAnonymously().await()
        refresh()
    }

    private suspend fun linkOrSignIn(auth: FirebaseAuth, credential: AuthCredential) {
        val user = auth.currentUser
        if (user == null || !user.isAnonymous) {
            auth.signInWithCredential(credential).await()
            return
        }
        try {
            user.linkWithCredential(credential).await()
        } catch (collision: FirebaseAuthUserCollisionException) {
            // The identity already owns an account (e.g. created on another device).
            // Switch to it; the anonymous session's cloud data is not merged.
            auth.signInWithCredential(collision.updatedCredential ?: credential).await()
        }
    }

    private fun webClientId(activity: Activity): String? {
        // Generated by the google-services plugin only when google-services.json exists.
        val id = activity.resources.getIdentifier("default_web_client_id", "string", activity.packageName)
        return if (id == 0) null else activity.getString(id)
    }

    private fun authOrNull(): FirebaseAuth? =
        if (runCatching { FirebaseApp.getInstance() }.isSuccess) FirebaseAuth.getInstance() else null

    private fun requireAuth(): FirebaseAuth =
        authOrNull() ?: throw IllegalStateException("Account services are not configured yet.")

    private fun refresh() {
        _account.value = snapshot(authOrNull()?.currentUser)
    }

    private fun snapshot(user: FirebaseUser?): AccountSnapshot {
        if (user == null) return AccountSnapshot()
        return AccountSnapshot(
            isSignedIn = true,
            isAnonymous = user.isAnonymous,
            email = user.email,
            providers = user.providerData.mapNotNull { AccountProvider.from(it.providerId) }
        )
    }
}

private suspend fun <T> Task<T>.await(): T = suspendCancellableCoroutine { continuation ->
    addOnSuccessListener { continuation.resume(it) }
    addOnFailureListener { continuation.resumeWithException(it) }
    addOnCanceledListener { continuation.cancel() }
}
